### ISSUE TITLE
사용자 프로필 사진/닉네임 동기화

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#10]
마이페이지에서 닉네임이나 프로필 사진 변경시 기존 작성된 글이나 댓글의 닉네임과 프로필 사진이 동시 변경 동기화 되게 개발
(사진 변경시 기존 글과 댓글이 변경된 사진으로 동기화 되고 이름 변경시도 기존 글과 댓글이 동기화 되게 해주세요. 사진, 이름 2개 모두다요)

**Comment by okwinus** [comment]
프로필 사진 변경시 변경이 안되네요;;; 어떨때는 되고 어떨되는 안되는데
확인좀 부탁드립니다...;;

**Comment by courage-work** [comment]
다시한번 확인해봤는데 모두 정상적으로 변경표시가 됩니다.
제가 재현해 볼 수 있도록 테스트하신 방법 부탁드립니다.

**Comment by okwinus** [comment]
다시 확인 했는데 잘 변경되네요 ^^

**Comment by okwinus** [comment]
- 프로필 사진 변경
프로필사진이 변경 다시 확인 했더니 안되는데 최적 이미지 사이즈나 특정 이미지 파일만 등록 가능한거지 모르겠네요.
체크 부탁드립니다.
