### ISSUE TITLE
모바일 교육 페이지 에러 수정 요청

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#100]
모바일 교육 페이지에서
교육후기 버튼을 아래 위로 움직이면서 누르면
1줄로 정리되서 안나오고 2줄로 나올때가 있네요.

그리고 강의내용, 강사소개 누르면
상단 몇센찌정도가 짤려서 나오네요.
간격이 버튼을 눌러도 잘 맞도록 수정 부탁드려요.

강의 신청 완료시 "완료팝업"만 뜨는것이 아니라 강의 신청 완료 페이지까지 만들려고 하는데요.
이 부분도 개발 요청 드리구요. 추가 비용이 있다면 말씀 해주세요.

**Comment by courage-work** [comment]
PC와 모바일 모두 각 항목에 탭을 배치하고 있습니다. (2차 기능개선 요구사항)
스크롤 하게될 경우 상단에 탭이 고정되는데 픽셀 단위로 값이 지정되다보니 미세하게 움직일때 탭이 중복해서 나오거나, 위치 고정에 어려움 있습니다.

탭은 상단에 1개만 고정을 하고 하단에 표현되는 탭은 다른 형태로 표시하도록 변경하면 좀 더 유연하게 처리가 가능합니다.

의견 부탁드립니다.
