### ISSUE TITLE
상단 팝업 배너관리

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#107]
추가 해봤는데 상단 적용이 안되네요.

**Comment by courage-work** [comment]
![image](https://user-images.githubusercontent.com/33827059/36466502-ef348dd0-171d-11e8-8040-0e97cfb594da.png)
위 메뉴에서 이벤트 배너 설정 정보 입력 후 저장하시면 노출이 됩니다.
시간이 설정되지 않아 노출되지 않았습니다.

**Comment by okwinus** [comment]
아~ 그렇군요. 다시 해보겟습니다.
