### ISSUE TITLE
팝업 배너 관리자 기능 추가

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#11]
PC에서도 모바일 상단 팝업처럼 PC상단 팝업 배너를 관리자에서 삽입 할 수 있는 관리자 기능 개발
(PC메인화면에서 별도 팝업창이 아닌 최상단에 삽입배너 기능을 말씀 드린것이구요. 
모바일에 노출되있는 상단 이벤트 배너랑 동일한 기능입니다. 
PC에서도 상단에 배너를 삽입 & 수정 할 수 있는 기능과 , 이미지 삽입&링크삽입, 노출&비노출 등
기능이 있으면 하구요. 
ex) http://9fx.co.kr << 이런 사이트 같은 기능입니다.
최대 3개까지 노출 될 수 있게 해주시구요.(자동 전환 되게 해주시구요. 전환 타임도 설정 할 수 있으면 하구요)

**Comment by courage-work** [comment]
배너가 노출되는 개수의 제한은 두지 않았습니다.
배너 노출의 개수는 관리자 페이지에서 사용/미사용으로 조정이 가능합니다.

**Comment by courage-work** [comment]
PC 화면 적용 완료

**Comment by okwinus** [comment]
관리자 배너관리에 상단 배너 등록 하는 버튼이 안보여서요.
아직 적용이 안된건가요??

**Comment by courage-work** [comment]
상단배너는 관리자 페이지의 이벤트관리 기능과 연결되어 있습니다.
기존 이벤트 배너가 표시되던걸 변경하였습니다.

이벤트관리의 기능을 확인해주세요

**Comment by okwinus** [comment]
추가 해봤는데 상단 적용이 안되네요.
