### ISSUE TITLE
PC단희쌤 공식일정

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#110]
마우스 올렸을때 자동으로 뜨는건 잘 개발됬는데요.
일정이 겹칠시 위 이미지처럼 다른일정까지 가려버려서 근처 일정은 아예 선택이 안되네요. 이런 경우는 어떻하죠??
![default](https://user-images.githubusercontent.com/33827059/36466894-98d8bde2-171f-11e8-9a33-988a8deb8482.png)

**Comment by courage-work** [comment]
현재는 X 버튼을 눌러 창을 닫은 후 겹쳐진 일정 확인이 가능합니다.
기능 수정에 대한 의견 있으면 알려주세요.

**Comment by okwinus** [comment]
일단 이렇게 하구요. 오픈하고 회원들 반응 보면서 유지보수시 수정 요청 드리겠습니다 ^^

**Comment by courage-work** [comment]
넵 그럼 해당 이슈는 종료처리 하겠습니다.
