### ISSUE TITLE
마이페이지 항목 제거 검토

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#111]
마이페이지의 회원정보 변경에 생년월일 항목이 존재합니다.
생년월일 항목의 수집이 필요하지 않으면 삭제할까 합니다.
의견 부탁드립니다.

**Comment by okwinus** [comment]
생년원일 수집은 필요하지 않습니다.
헌데 삭제 하려는 이유는 개인정보수집 불법 소지 때문에 그런가요?

**Comment by courage-work** [comment]
개인정보의 사유와 PC에서는 이미 제거된 항목임을 확인했습니다.
