### ISSUE TITLE
노하우정보집 업로드 용량 수정 요청

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#115]
20M 이상의 파일은 안올라가는것 같은데
관리자는 용량 제한은 풀 수 있을까요?

일반유저는 당연히 제한이 있구요.
일밭유저는 다른 게시판을 예를 든것입니다.

**Comment by courage-work** [comment]
용량제한을 모두 변경하는것은 유지보수 범위로 가능합니다.
권한별 용량 제한은 기능이 추가 및 수정되어야 합니다.
위 사항 고려하시고 의견 부탁드립니다.
