### ISSUE TITLE
2018.3.2(금) 오픈 전 최우선 개발내용 총정리

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#116]
★최우선 급한 사항 3.1(목) 오픈전까지 가능하다면 부탁드립니다.
    도저히 불가능한 사항이 있다면 말씀 해주세요. 

▶메인 메뉴바 수정
위에서 말씀 드린것처럼 PC와 모바일 모두 메인 메뉴바에서 "멤버십VIP"가 사라지면
메인 메뉴바가 6개가 되서요.
남은 공간을 적절히 여유공간을 두고 배치 해주세요.

▶네이버, 페이스북 회원가입 안됨
네이버, 페이스북 회원가입시 "가입"버튼을 누르면 안되네요. 체크 부탁드립니다.

▶비로그인 사용자 권한
- 부동산재테크정보
- 인생2막준비
- 노하우정보집
- 단희TV
- 커뮤니티

위 3개 메뉴를 비로그인자도 들어갈 수 있게는 해주시구요.
들어가서 글을 열람 하려고 하면 로그인 하라는 메세지가 뜨게 변경 해주세요.
아예 못들어가서는 안됩니다.

그리고 커뮤니티는 비로그인 사용자도 
글은 볼 수 있게 하고 글 작성은 로그인 해서 할 수 있게 해주세요.

▶멤버십VIP 메뉴
PC에서 상단 "멤버십VIP"메뉴를 우측 상단의 검은색 바 메뉴로 옮겨주세요.
위치는 마이페이지 옆 오른쪽에 배치 해주시구요.
즐겨찾기는 가장 우측으로 밀어주세요.

모바일에서는 멤버십VIP 메뉴를 상단 메뉴바랑 왼쪽 네비게이션 바에서 제거 해주시고
제거된 멤버십VIP 메뉴를 왼쪽 네비게이션 바 "마이페이지" 하단에 배치 해주세요.

메뉴별 권한은

- 멤버십VIP소개, VIP서비스9가지 소개 
2개의 메뉴는 비로그인 사용자도 볼 수 있게 해주시구요.

- VIP재테크정보
VIP재테크정보 메뉴는 들어는 가지는데 실제 콘텐츠를 누르고 들어가려면
VIP권한이 없을 경우 열람이 안되게 해주세요.

- VIP상담신청
접속은 되는데 상담신청은 VIP권하느 있는 사람만 할 수 있게 해주세요.

- VIP물건소개
VIP권한이 없는 사람 같은 경우 접근 자체가 안되게 해주세요.

▶재테크성공사례
모바일에서 이미지 확인이 안됩니다. 

▶인생2막준비 메뉴 열람권한 지정
부동산재테크정보, 노하우정보집, 단희TV 처럼 인생2막준비 메뉴 콘텐츠도
콘텐츠 등록시 FAMILY, MEMBER, VIP 권한 지정 할 수 있게 해주세요.

▶부동산재테크 정보
일반회원이 콘텐츠 열람시 0포인트 소진된다고 나오는데
이 메세지를 제거 해주시고 바로 열람 할 수 있게 해주세요.
부동산재테크정보는 일반회원도 포인트 소진 없이 바로 볼 수 있습니다.

▶MEMBER(연간회원) 콘텐츠열람 권한 수정
연간회원은 유료 정액회원이라 모든 콘텐츠를 포인트 소진 없이 볼 수 있습니다.
노하우정보집과 단희TV 열람시 포인트 소진이 안되고 바로 볼 수 있게 해주세요.

▶VIP회원 콘텐츠열람 권한 수정
VIP회원인데도 VIP재테크정보를 못보네요.  VIP상담신청도 안됩니다.
VIP회원도 단희TV하고 노하우정보집 콘텐츠 열람시 포인트 소진 없이 바로 볼수 있게 해주세요.

▶회원등급별 콘텐츠열람 권한 총정리
열람권한의 정의는 메뉴 자체에 접근을 못하는것은 아니고
접속은 가능하나 콘텐츠를 누르고 들어갈시 열람이 안된다는것을 뜻함

- 비회원 열람 가능 메뉴 : 
단희부동산소개, 교육/상담, 멤버십VIP소개, 9가지서비스 소개, 고객센터, 커뮤니티

- 일반회원만 FAMILY 열람 가능 메뉴 : 
비회원 열람 가능 모두 가능, 부동산재테크정보&인생2막준비 포인트 소진 없이 열람 가능
단희TV, 노하우정보집 포인트 소진 후 열람 가능

- 연간회원 MEMBER 열람 가능 메뉴 : 
비회원 열람 가능 모두 가능, 
부동산재테크정보&인생2막준비&노하우정보집&단희TV 포인트 소진 없이 열람 가능

- VIP 열람 가능 메뉴 : 
모든 메뉴 포인트 소진 없이 열람 가능

▶모바일에서 교육 썸네일 이미지 찌그러짐
모바일에서 교육 썸네일 이미지가 찌그러져서 나옵니다.

▶스탭메일 및 메일발송시 발신자명 수정
현재는 메일 발송시 발신자명이 webmaster@danhee.co.kr로 나오는데요.
"단희쌤"으로 발신자명을 바꿔주시구요.
발신자이메일은 okwinus@danhee.co.kr로 변경 해주세요.

▶메뉴명 동기화 및 수정(PC+모바일 모두 동기화)
- PC&모바일메인 -> 교육받은 분들의 REAL 교육후기 => "강연&상담 후기" 변경
- PC&모바일메인 -> 단희쌤과 함께한 성공 사례 => "상담&컨설팅 사례" 변경
- 교육/상담 -> 재테크성공사례 => "상담&컨설팅 사례" 변경 (상단메뉴바의 전체메뉴바도 변경)
- 교육/상담 -> 부동산재테크강연 => "교육/세미나" 변경
- 교육/상담 -> 부동산재테크상담 => "상담/컨설팅" 변경
- 교육/상담 => 상단 서브배너의 "부동산서비스" 문구를 "교육/상담 서비스"로 변경
- 부동산재테크정보 -> 상담&컨설팅 사례 => "성공/실패사례" 변경
- 인생2막준비 모든 하위 4개 메뉴 상단메뉴바의 전체메뉴에 들어가있는 메뉴명으로 모두 동기화
- 단희TV 하위메뉴 4개 변경/동기화 "부동산재테크정보, 재테크성공사례, 인생2막준비, 인생2막실전"

최종 확정 메뉴입니다.
이전 요구사항은 무시 해주세요.

▶메뉴 삭제
부동산재테크정보 -> 은퇴준비 => 은퇴준비 메뉴 삭제 해주세요.

▶더보기 버튼 수정
아래 메뉴에 있는 더보기 메뉴를 PC 모바일 없애 주시구요.
일반 게시판처럼(ex 공지사항, 커뮤니티 등) 아래 페이지 숫자가 나와서
각 페이지 숫자를 눌러서 이동하게 하려고 합니다.
한페이지에 나오는 게시물 줄 수는 PC는 3줄, 모바일은 4줄까지 나오게 해주시고
그 다음은 페이지가 변환되어 다음 페이지로 넘어 갈 수 있게 추가 해주세요.

더보기 수정 페이지 리스트

단희쌤 언론보도&수상
교육
강연&상담후기
재테크 성공사례
VIP재테크정보
부동산재테크정보
인생2막준비
노하우정보집
단희TV
더보기 버튼 수정 예정 페이지

▶콘텐츠 표시 변경
![image](https://user-images.githubusercontent.com/33860901/36582250-0d45d238-18b4-11e8-93da-89cdd87201ad.png)

각 콘텐츠마다 조회수, 좋아요, 댓글, 공유 이렇게 4개가 나왔는데요.
너무 많아서 잘 안보이는듯 하여 2개로 축소하기로 했습니다.
​
조회수, 좋아요만 나오게 전체 모두 변경 해주시구요.
4자리 천단위 숫자는 그대로 나오고 만단위고 넘어가면 저렇게 나오게 해주세요.

▶PC (단희쌤 언론보도&수상 콘텐츠 정렬 점검
카테고리 점검

전체 : 전체 콘텐츠가 안나옵니다.
수상내역 : 더보기가 안눌러집니다.(더보기 없애지면 상관 없습니다. 있는 상태에서는 수정)
언론보도 : 더보기가 안눌러집니다.(더보기 없애지면 상관 없습니다. 있는 상태에서는 수정)

▶노하우정보집
PC : 이미지가 화면을 벗어나서 안좋게 나오네요. 
모바일 : 세로로 길게 늘어트려서 길게 나옵니다.

▶PC 회원가입 화면 상단배너 이미지 에러
회원가입 화면 상단 비주얼 배너 이미지가 이상하게 나오네요. 확인 부탁드려요.

▶PC메인 노하우정보집 표현 변경
![image](https://user-images.githubusercontent.com/33860901/36582412-b908e70e-18b4-11e8-8aa3-562753d21be3.png)
현재 PC메인에서 노하우정보집이 이렇게 표시 되는데요.

![image](https://user-images.githubusercontent.com/33860901/36582416-bc3ce31c-18b4-11e8-93cf-aa3743637237.png)
위 이미지처럼 조회수, 좋아요 부분의 바탕 색을 흰색으로 변경 해주시고
썸네일 하단의 파란색 글씨와 검은색 요약글처럼 2개 나오게 하지 마시고
위 위미지처럼 검은색으로 제목만 나오게 변경 해주세요.
(날짜는 표시 안해도 됩니다)

그리고 지금은 한줄에 4개씩 나오는데요. 3개 나오게 변경 해주세요.

▶PC 메인 단희TV 표시방법 변경
![image](https://user-images.githubusercontent.com/33860901/36582467-f35b17ce-18b4-11e8-868b-7695f5c6c5f5.png)

현재 썸네일 이미지에 파란색 이미지가 덧 씌워저 있는데요.
덧 씌워진 이미지를 없애주세요.
그리고 현재 단희TV 썸네일 이미지는 중앙에 재생 표시가 나와있는데
메인에서는 그 이미지가 안나오네요. 수정된 이미지가 안나오는 부분 체크 해주세요.

그리고 PC 메인 단희TV에도 각 콘텐츠 하단에 조회수, 좋아요 표시가 나오게 해주세요.

유의사항 주신것 고려해도 없애는게 좋을것 같습니다.
제목과 재생표시는 썸네일 이미지를 올릴때 통일화 해서 잘 보이게 디자인 편집 하려고 합니다.

▶기존 포인트 팡팡 룰렛 페이지
기존 이벤트 페이지 URL이 어떻게 되죠? 그 페이지도 활용 해야 해서요.

▶PC+모바일 메인 "단희쌤의 특별한 선물 4가지" 링크
PC+모바일 메인 "단희쌤의 특별한 선물 4가지" 링크

새로 개발된 내용인데요.
각각의 "바로가기" 버튼을 누르면 해당 메뉴의 게시판으로 넘어 갈 수 있게
링크를 적용 해주세요.

▶PC+모바일 콘텐츠 정렬 변경
![image](https://user-images.githubusercontent.com/33860901/36582565-65714e64-18b5-11e8-9205-4c424be252ac.png)

메인에서 부동산재테크 정보 부분을
위 이미지처럼 부동산재테크 정보 1줄
인생2막준비 정보 1줄
이런 형태로 변경 ㅎ ㅐ주시구요.

모바일 메인도 부동산재테크 정보 하단에 인생2막 준비 콘텐츠가 나오게 추가 해주세요.
노출형태는 부동산재테크정보랑 동일 하면 됩니다.

▶모바일 메인 노하우정보집 표시 방법 변경
모바일 메인의 노하우정보집 콘텐츠 표시 방법을

모바일 메인 "부동산재테크" 정보 형태처럼
한줄에 2개씩 그리고 부동산재테크 처럼 손가락으로 드래그도 가능하게 해주시구요.
그냥 부동산재테크 정보 메인처럼 똑같이 형태를 변경 해주세요.
현재 한줄에 3개라서 책아 이미지가 잘 안보여서 그렇습니다.

▶모바일 메인 단희TV 표시방법 변경
단희TV 메인 모바일도
부동산재테크정보 처럼 2단 형태로 콘텐츠가 노출될 수 있게 변경 해주세요.

▶PC교육 페이지 에러 수정
![image](https://user-images.githubusercontent.com/33860901/36582690-c2c8f62a-18b5-11e8-8c7d-9736ac8f235f.png)

강의내용 강사소개 탭은 눌르면 제대로 되는데
강연장소, 관련강의, 교육후기는 눌러도 해당 탭의 색상이 파란색으로 안나오네요.
체크 부탁드리구요.

전체적으로 탭 버튼을 누르면 탭 내용의 상단 부분이 잘려서 노출될때가 있네요.
간격이 잘 맞을수 있도록 수정 부탁드리구요.

강의 신청 완료시 "완료팝업"만 뜨는것이 아니라 강의 신청 완료 페이지까지 만들려고 하는데요.
이 부분도 개발 요청 드리구요. 추가 비용이 있다면 말씀 해주세요.

완료페이지 메세지는 "강연신청이 완료 되었습니다." 일단 이렇게 간단한 한줄로 해주시구요.
추후 유지보수 개발시 추가 하도록 하겠습니다.

▶모바일 교육 페이지 에러 수정 요청
모바일 교육 페이지에서
교육후기 버튼을 아래 위로 움직이면서 누르면
1줄로 정리되서 안나오고 2줄로 나올때가 있네요.

그리고 강의내용, 강사소개 누르면
상단 몇센찌정도가 짤려서 나오네요.
간격이 버튼을 눌러도 잘 맞도록 수정 부탁드려요.

강의 신청 완료시 "완료팝업"만 뜨는것이 아니라 강의 신청 완료 페이지까지 만들려고 하는데요.
이 부분도 개발 요청 드리구요. 추가 비용이 있다면 말씀 해주세요.

상단 탭과 하단탭이 표시되는 방법이 크게 다르지 않으면
유연하게 처리가 가능한 방법으로 해주세요.
무슨 형태인지는 말씀만으로 잘 이해는 가지 않습니다.

▶강연&상담 후기 & 성공/실패사례 디자인 변경
PC&모바일 표시
PC하고 모바일 모두 아래 형태로 변경 해주세요.
이름 크기를 조금 키웠구요. 요약내용 나오는것을 2줄까지 나오게 했습니다.
조회수, 좋아요만 남기고 삭제했고(앞에 나오는 같은 내용입니다) 조금 키웠습니다.
PC 모바일 둘다 이런형태로 나오게 해주세요.

![image](https://user-images.githubusercontent.com/33860901/36582852-6e988358-18b6-11e8-8ce0-3bfa25781ba8.png)

성공/실패사례도 같은 형태로 해주시되 1줄에 1개씩 길게 나오니 적절히 배치 해주세요.
요약글도 2줄까지 나오게 해주세요.

====================================================
★2순위 급한 사항 - 오픈 이후 우선 개발해야 할 사항

▶신청완료 페이지 추가 개발
강연 신청 완료 페이지, 상담신청 완료 페이지, VIP상담신청 완료 페이지, 회원가입완료 페이지
완료페이지 메세지는 간단하게 이런식으로 해주세요.

- 강연신청 완료페이지 => "강연신청이 완료 되었습니다."
- 상담신청 완료 페이지 => "상담신청이 완료 되었습니다."
- VIP상담신청 완료페이지 => "VIP상담신청이 완료 되었습니다."
- 회원가입완료 페이지 => "회원가입을 축하드립니다."

일단 이렇게 간단한 한줄로 해주시구요.
추후 유지보수 개발시 추가 하도록 하겠습니다.

▶멤버 등급 변경시 댓글 프로필 동기화 안됨
멤버등급 변경을 하고 댓글 등록을 하면
등록이 되어있는 댓글프로필은 동기화가 되는데
댓글 등록하는 창의 프로필은 동기화가 안됩니다.

▶첨부파일 용량 제한
권한 상관없이 모든 첨부파일 용량 제한을 모두 변경 해주세요.
나중에 서버에 무리가 가면 그때 추가 개발을 하면 될 것 같아요.
현재 회원들이 글을 적고 첨부파일을 올릴공간이 많지 않아서 괜찮을거 같습니다.

▶PC상단 메뉴바
![image](https://user-images.githubusercontent.com/33860901/36582315-5fa5b1ce-18b4-11e8-9bd1-c5f789010ffb.png)

PC상단 메뉴바 아래로 스크롤 내릴시 파란색 메뉴바가 검은색 상단바에 
자연스럽게 붙으면서 로고가 사라지게 해주세요. 
콘텐츠 나오는 공간이 작아서 이렇게 변경하려 합니다.

▶모바일 상단 메뉴바
상단에 있는 파란색 메뉴바를 변경 하려 합니다.
"홈" 버튼을 없애 주시구요.
좌우측에 있는 < > 버튼을 없애고 
우측에 " V " 버튼을 누르면 모든 메뉴가 전부 나올수 있게 해주세요.
메인 메뉴바 뿐만 아니라 하위 메뉴들까지 이런 형태로 모두 변경 합니다.
40대분들이 이 메뉴가 익숙치 않다는 피드벡이 많아서 변경 하려 합니다.

▶PC메인 배너 수정
![image](https://user-images.githubusercontent.com/33860901/36582631-91886bf4-18b5-11e8-8cbb-0c8e5f2df117.png)

PC메인에서 수상이력 배너를 위 배너로 변경 해주세요.
문구가 일부 변경 되었습니다. 원본파일 필요하시면 말씀 해주세요. 보내드리겠습니다.

▶네이버 사이트설명 문구 수정
![image](https://user-images.githubusercontent.com/33860901/36582658-a59b1af6-18b5-11e8-9710-695de72e2d70.png)

네이버 사이트 설명 문구를 아래 내용으로 변경 해주세요.
"3년내 은퇴하려는 40대 직장인을위한 부동산재테크 / 무료소책자 10권, 무료 동영상강의 제공"

====================================================
★3순위 사항 - 당장 급하지 않은 나중에 해도 될 사항

▶강연마감 색상 변경
현재 검정색을 주황색으로 변경 해주세요. 
마감된 강연을 회색으로 흐리게 해주시구요.

▶통합검색 검색시 나오는 요약글 내용
통합검색시 나오는 요약글이 너무 조금 나와서요.
최소 2줄까지 나오게 해주시고
제목과 요약글의 폰트 크기를 조금더 키워주세요. 너무 쪼그마네요.

▶콘텐츠 공유
콘텐츠 공유시 제목은 가져와 지는데
미리보기 썸네일 이미지와 내용은 안가저와 지네요.

▶프로필 사진 변경
프로필사진이 변경 다시 확인 했더니 안되는데 최적 이미지 사이즈나 
특정 이미지 파일만 등록 가능한거지 모르겠네요.
체크 부탁드립니다.

▶모바일 단희쌤공식 일정
월간 공식일정의 세로폭을 조금 더 넓혀주세요.
세로가 좁아서 비좁아 보이네요.

▶SEO작업
SEO작업은 어떤 범위인지 어떤 내용인지 알 수 있을까요?

▶마이페이지 프로필변경&회원정보 변경 글씨 크기 조정
안에 들어가 있는 글씨의 크기를 조금만 더 키워주세요.
글씨가 작아서 눈이 침침해 잘 안보일것 같습니다;;;

▶보안 관련 추가 개발 견적
전에 미팅때 말씀 해주신
보안 관련된 추가 견적 내용 부탁드립니다

▶모바일 왼쪽 전체메뉴 에러 수정 요청
![image](https://user-images.githubusercontent.com/33860901/36582389-a2652814-18b4-11e8-9f30-01da0633cd66.png)

모바일 왼쪽 상단 메뉴를 누르고
손가락으로 아래로 내리면 메뉴가 위로 밀리면서 사라져 버립니다.
다른 사이트 같은 경우 전체메뉴가 뜨면 아래 위로 스크롤 자체가 안되는데
저의 사이트는 이렇게 되네요. 이 부분도 수정 부탁드립니다.

개발이 필요하다면 견적 주시구요.

▶관리자 페이지에서 "사용자관리" VIP D-day 기일 표시 에러
연간회원 MEMBER과 VIP회원의 D-day가 카운트 되서 변경이 안되고
365일로 고정되어 있네요.

▶이미지 사이즈 자동 조정
안하겠습니다. 일이 커질것 같네요 ^^;;

**Comment by courage-work** [comment]
기존 포인트 팡팡 이벤트 페이지의 URL은 아래와 같습니다.
https://www.danhee.co.kr/event/roulette.html

위 html의 경우 변경된 디자인의 css가 적용되지 않아 메뉴 등 정상적으로 표시되지 않고 있습니다.
