### ISSUE TITLE
[안내 및 문의]

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#121]
페이징 처리와 domain 전환 관련하여 안내 드립니다.

현재 PC와 모바일의 페이징 처리 기준이 다르게 설정되어 있습니다.
(하나의 페이지에 표시되는 컨텐츠 개수가 다름)

예로 교육/세미나의 두번째 페이지에 표시되는 컨텐츠는 PC와 모바일이 각각 다를 것입니다.

위와같은 상황에서 PC에서 복사한 URL을 공유하고 사용자들이 모바일로 접근할 경우 의도치 않은 상황이 발생될 수 있습니다. (반대로 Mobile URL을 공유하고 PC로 접근했을때도 같습니다.)

동일한 정보접근을 위해선 Mobile과 PC의 페이징 처리 기준이 같아야 하지 않을까란 생각이 들어 글 남겨드립니다.

이와 관련해 의견 있으면 댓글 부탁드립니다.

**Comment by okwinus** [comment]
같은게 좋을것 같아요. 혼란스러운 상황이 생기면 안되니까요

**Comment by courage-work** [comment]
페이지당 표시되는 개수를 PC와 모바일 동일하게 변경하겠습니다.
