### ISSUE TITLE
내가 저장한 컨텐츠 수정 요청

### ISSUE THREAD

**Issue by dg828** [courage-work/danhee#123]
사이트에서 컨텐츠를 본 후에 저장하기 누르고 마이페이지에서 확인하면
글 제목은 안보이고 메뉴만 보입니다.

글 제목이 보일 수 있도록 수정 부탁드립니다.

**Comment by courage-work** [comment]
마이페이지 내가 저장한 글을 확인해본 결과 정상적으로 표시되는 것 같습니다.
제가 위 사항을 재현해 볼 수 있도록 저장기능을 이용하신 메뉴와 컨텐츠를 알려주시기 바랍니다.

**Comment by courage-work** [comment]
PC에서는 정상이고 모바일에서 위의 현사이 발생됨을 확인하고 수정했습니다.
다음에 이상현상이 발생된다면 꼭 PC/Mobile 구분과 메뉴명을 함께 알려주시기 바랍니다.

**Comment by okwinus** [comment]
다음부터는 구분 해서 알릴수 있도록 하겠습니다.
