### ISSUE TITLE
오타와 오류 발견

### ISSUE THREAD

**Issue by dg828** [courage-work/danhee#125]
[오타 관련]
1. 모바일 메인 페이지
재테크 강의"단희TV" 에서 재테크 강의"단희TV"로 수정해주세요.
![kakaotalk_20180312_121736100](https://user-images.githubusercontent.com/33975688/37264340-29ed45f8-25f0-11e8-88b4-c67cdc444bf8.png)

2. 모바일 단희부동산 소개 페이지
단희쌤 프로필&이력에 들어가서 업무실행 누르면 업무싱행이라고 나오는데 업무실행으로 수정 부탁드립니다.
![kakaotalk_20180312_121736357](https://user-images.githubusercontent.com/33975688/37264374-6173338e-25f0-11e8-92bb-12f7c2bdd36d.png)

[오류 발견]
회원이 댓글을 길게 남길 경우에 댓글이 끝까지 보이지 않습니다.
아래 이미지는 단희부동산소개 → 단희부동산소개 목차에 있는 댓글을 캡쳐한 것입니다.
![kakaotalk_20180312_121736560](https://user-images.githubusercontent.com/33975688/37264427-9f46c504-25f0-11e8-8ac5-272e9c8b949c.png)

**Comment by courage-work** [comment]
1. 모바일 메인 페이지
재테크 강의"단희TV" 에서 재테크 강의"단희TV"로 수정해주세요.
 => 해당 화면은 이미지로 작업을 의뢰하셨던 디자이너에게 오타 수정 부탁드립니다.

2. 이아상 대표 업무싱행 오타
 => 이의상 대표 업무실행 으로 수정

3. [오류 발견]
회원이 댓글을 길게 남길 경우에 댓글이 끝까지 보이지 않습니다.
아래 이미지는 단희부동산소개 → 단희부동산소개 목차에 있는 댓글을 캡쳐한 것입니다.
 => 원 개발사의 의도된 기능으로 확인 됩니다. 모두 표시되도록 수정하겠습니다.
