### ISSUE TITLE
크롬 Notifications 기능 추가

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#13]
https://center-pf.kakao.com/notices/68
위 주소 들어가시면 카카오톡 비즈니스 계정 "플러스친구" 신규 기능인데요.
유튜브나 페이스북도 동일한 기능이 있는데
특정 게시판에 글이 올라올때
크롬브라우저 에서는 우측 하단에 알림창이 뜨게 하던데요.
웹사이트에 접속을 안한 상태에서도요.

이런식의 개발이 가능한가요?
원하는 특정 게시판에 글이 작성 될 때 우측 하단에 알림창이 뜨게 하거나
댓글 등의 행동이 일어났을때도요

-> 부동산재테크 강연 등록시, 상담 접수 완료, 부동산재테크정보&노하우정보집&단희TV 글 등록시, 공지사항 글 등록시

**Comment by courage-work** [comment]
알람의 경우 사용자가 알람받기 (또는 구독하기) 등 직접 설정 후 알람을 받을 수 있습니다.
스마트폰 앱으로 생각하시면 푸시 수신동의 하는 과정과 똑같다고 보시면 됩니다.

알람받기 설정을 어떻게 배치하면 좋을지 의견 부탁드립니다.
제 의견은 다음과 같습니다.
1. 알람설정에 대해 마이페이지에 알람수신 항목을 추가한다.
2. 로그인 사용자가 알람설정이 안되어 있을경우 메시지 표시지 마이페이지로 이동한다. (알람거부자는 제외)

추가로 알람기능을 사용하기 위해선 홈페이지 보안조치가 강화되어야 합니다.
주요 포털사이트 접속주소를 보시면 http가 아닌 https로 시작하는걸 자주 보셨을 겁니다.
https는 브라우저와 서버간에 데이터를 암/복호화 처리를 통해 보호하는 통신 프로토콜 입니다.
https를 적용된 사이트를 대상으로만 알람 발송 기능을 제공하고 있으니 반드시 https를 반영해야 합니다.

절차는 다음과 같습니다.
1. SSL (https) 인증서 발급 - 유료이며, 인증서 유효기간에 따라 가격 차등
2. SSL 인증서 설치 및 서버 설정 (추가 작업비 발생 5만원)

참고로 개인정보를 다루는 사이트는 법적으로 반드시 SSL을 적용토록 되어 있으니, 이번기회에 작업해서 보안강화를 진행하면 좋을거 같습니다.

인증서는 3년짜리도 5만원 미만 입니다.
https://www.qtrustssl.com 인증서 판매 사이트 Positive SSL 인증서 구매하시면 됩니다.

**Comment by okwinus** [comment]
알겠습니다. 진행 하겠습니다.
안그래도 보안 때문에 걱정이었는데 잘됬네요.
인증서 구매만 하고 말씀 드리면 되나요?

**Comment by courage-work** [comment]
인증서 안내 드릴때 모바일 홈페이지 인증서를 빼고 말씀드렸네요 ^^;
m.danhee.co.kr 도메인에 대한 인증서도 구매 부탁드립니다.
방법은 전과 동일하게 진행해 주시면 됩니다.

**Comment by okwinus** [comment]
발급중입니다. 인증메일 오는데로 전달 드리겠습니다 ^^
