### ISSUE TITLE
단희캠퍼스 로고 수정

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#131]
![default](https://user-images.githubusercontent.com/33860901/37942354-9d88e814-31ad-11e8-80a4-c69146edcd44.jpg)

PC 하단에 있는 단희캠퍼스 로고를 위 파일로 변경 해주세요.

**Comment by courage-work** [comment]
위 이미지를 수정해서 했더니 해상도가 낮아 품질이 떨어져 보입니다.
원본 파일 또는 폭 150px 사이즈의 png 파일을 부탁드립니다.
