### ISSUE TITLE
강연&상담후기 수정 오류

### ISSUE THREAD

**Issue by dg828** [courage-work/danhee#135]
안녕하세요 개발자님

"교육/상담"에서 "강연&상담후기"에 글을 적고 글을 적은 계정으로 
수정을 눌렀더니 수정 권한이 없다고 나와서요.
글을 적은 계정으로는 수정이 가능하면 좋겠습니다.

이 부분 확인해주시면 감사하겠습니다!

**Comment by courage-work** [comment]
확인결과 수정/삭제 모두 정상적으로 작동되는 것으로 확인했습니다.
위의 상황이 발생한 아이디와 작성글이 무엇인지 알려주시면 확인해보겠습니다.

**Comment by dg828** [comment]
![20180410_153042](https://user-images.githubusercontent.com/33975688/38539702-2eb42fe8-3cd4-11e8-8995-5048ef8ef719.png)
![20180410_153055](https://user-images.githubusercontent.com/33975688/38539703-2f00cbf0-3cd4-11e8-9595-ed3d71a9ca0e.png)
작성한 아이디로 수정을 눌렀더니 이렇게 나옵니다.

아래이미지에 있는 글 전부 각각 다른아이디로 제가 작성했는데 전부 수정 권한이 없다고 나와요.
확인부탁드립니다!
![20180410_153128](https://user-images.githubusercontent.com/33975688/38539758-6396d58a-3cd4-11e8-8b62-e78bdc12a25f.png)
