### ISSUE TITLE
강연&상담후기 카테고리

### ISSUE THREAD

**Issue by dg828** [courage-work/danhee#136]
안녕하세요!

교육/상담에서 강연&상담후기에 있는 카테고리 문구를 관리자페이지에서 변경못하나요?

기존에 "생생영상후기", 강연상담후기"에서
"강연/세미나 후기", "상담 후기" 로 변경하고 싶습니다.

**Comment by courage-work** [comment]
해당 정보는 고정값을 사용하도록 되어 있습니다.
카테고리와 같이 변경하려면 기능수정이 필요한 건입니다.
우선 명칭변경은 처리하겠습니다.
