### ISSUE TITLE
PC메인화면 동영상 썸네일 수정

### ISSUE THREAD

**Issue by dg828** [courage-work/danhee#138]
![20180409_173214](https://user-images.githubusercontent.com/33975688/38490547-5848e07a-3c24-11e8-83b7-b0108674e367.png)

PC 메인에서 보면 이미지에 나와있는 것처럼 동영상 썸네일과 제목이 겹쳐서 나와서요.
PC메인에서는 아예 제목을 안나오게 해주시면 감사하겠습니다!

**Comment by courage-work** [comment]
메인 화면의 단희 TV 컨텐츠의 디자인 수정은 다음과 같이 진행 되었습니다.

1. 투명 백그라운드 파랑색이 오버레이 되어 표시 되었음.
 - 오버레이 배경으로 흰색 제목이 자연스럽게 표시됨

2. 투명 백그라운드 제거를 요청함.
 - 제목이 위와같이 표시될 수 있음을 안내함
 - 썸네일 이미지의 변경을 통해 제목이 잘 보여질 수 있도록 변경 예정이라고 함

위와같은 진행내역이 있었습니다.
혹시 썸네일 이미지 변경 없는 것인가요?
제목을 제거할 경우 하기 화면에 제목이 표시되지 않을 것입니다.
확인 부탁드립니다.

![image](https://user-images.githubusercontent.com/33827059/38539120-b7723bd4-3cd1-11e8-931a-f7865b377b9c.png)
