### ISSUE TITLE
스탭메일 발송

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#14]
각 단계 유동 조절(단계수&시간차, 내용 수정)
현재 관리자 기능에 메일발송 기능이 있는데요. 이 관리자 기능을 이렇게 수정 부탁합니다.

회원이 최초 회원가입시 자동으로 발송 되는 메일 내용을 HTML에디터 기능까지 해서 수정 등록 할 수 있는 기능과

최초 메일 이후 최대 10번메일이 자동 발송되게 기능 개발을 하려고 합니다.
풀어서 설명 드리면

- 최초 회원가입시 자동 메일 발송
- 가입 후 1일 후 자동 메일 발송
- 가입 후 2일 후 자동 메일 발송

이런식입니다. 
각 메일을 보내는 일자와 시간을 수정 하는 기능과 내용도 각 단계마다 수정 할 수 있는 기능도 있으면 하구요.

관리자에서 설정 하는 조건에 따라서 자동메일 발송을 몇번 보낼것인지와, 각 메일마다 시간 간격, 내용 수정/등록 등
스탭메일 기능을 개발하려고 합니다.

**Comment by courage-work** [comment]
메일 양식 관리관련 문의 드립니다.

1. 메일양식 관리 에디터 문의
제가 테스트한 결과 HTML 에디터로 양식을 관리할 경우 HTML 에디터에서 제공하는 기능으로만 양식관리가 가능합니다.

예를 들어 Html 소스코드 보기로 소스를 수정한 경우 에디터에서 자동으로 수정한 코드를 변환해 버립니다.
에디터에서 Html 소스코드 수정의 범위를 제한하고 있는 것으로 확인 됩니다.

보통은 메일양식을 Html 소스코드로 관리하는게 일반적이긴 합니다.
현재 관리자 페이지의 메일관리 > 양식관리와 같은 형태로 말이죠.
양식을 디자이너가 Html작성하면 해당 Html 소스를 복사 & 붙여넣기 하는 방식으로 진행하죠.

위 내용 고려하셔서 결정해주시면 진행하겠습니다.

2. 가변항목 처리 안내
회원가입시 가변으로 처리할 수 있는 항목은 다음과 같습니다. 참고 부탁드립니다.
아이디, 이름, 이메일, 전화번호, 가입일자, 등급

가변항목은 "안녕하세요 ${이름} 고객님." 과 같은 형태로 사용됩니다.

**Comment by okwinus** [comment]
메일 보내는 양식은  
HTML에디터 기능 없이
현재 메일양식처럼 소스코드 붙여넣기로 진행 해주세요.
현재 뉴스레터도 그렇게 보내고 있습니다.

**Comment by courage-work** [comment]
회원가입시 메일수신 여부가 "수신하지 않음"의 경우 회원가입 안내 메일을 발송할지에 대한 결정 부탁드립니다.

**Comment by okwinus** [comment]
수신하지 않음으로 되어 있으면 보내지 말아주세요. 법적으로도 안되는걸로 알고 있어요.
다만 처음 가입시 "수신함"으로 자동 체크되게 해주세요.

**Comment by okwinus** [comment]
가변 항목 테스트를 했는데 이름이 변경 되서 안가네요. 
제가 설정한 부분이 잘못된것이 있는지 체크 부탁드립니다.
