### ISSUE TITLE
페이스북 회원가입 시 facebook이메일 작성 제거 

### ISSUE THREAD

**Issue by dg828** [courage-work/danhee#140]
![20180409_162144](https://user-images.githubusercontent.com/33975688/38529524-2e5a1b4a-3ca0-11e8-9bca-c773c73e6465.png)

페이스북으로 회원가입 시 facebook이메일이랑 이메일을 적으라고 나오는데요.
facebook 이메일은 빼도 될 거 같아서요.
빼주시면 감사하겠습니다!

**Comment by courage-work** [comment]
facebook 이메일의 경우 계정 연동을 위해 사용되는 정보로 사용자 입력항목은 아니고 자동으로 기입되는 항목입니다.
facebook 이메일 항목은 노출을 숨겨 사용자가 두번 입력하는것 처럼 보이지 않도록 하겠습니다.
facebook외의 naver, kakao도 동일하게 변경하겠습니다.
