### ISSUE TITLE
노하우정보집 메뉴 수정

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#146]
노하우정보집 메뉴에서
해당 책자 메뉴로 들어갈때 포인트 열람 메뉴가 나오는데요.

들어갈때 포인트 열람이 나오지 않고
해당글로 들어가서 "소책자 다운받기" 버튼을 누를때 포인트 열람이 나오게 할 수 있나요?

그리고 소책자파일이  PDF파일인데 다운받기가 아닌
바로보기 식으로 할수도 있나요?

**Comment by courage-work** [comment]
adobe reader가 설치된 사용자에 한해서 바로보기가 가능합니다.
설치된 사용자는 바로보기, 이외의 사용자는 다운로드 되도록 하면 될거 같아요.

**Comment by okwinus** [comment]
네 제가 알기로 요즘 스마트폰에 한컴뷰어 같이 기본 앱이 깔려 있다고 해서요
PC는 물론 어도브 리더가 있어야 겠지만
모바일 사용자가 많아서요

해당 기능으로 기능 개발 부탁드려요

**Comment by courage-work** [comment]
노하우 정보집 소책자 다운받기시 포인트 다운로드로 변경이 되었습니다.
상단에 있는 첨부파일명을 클릭하여 다운로드시 구매안내 메시지가 표시됩니다.

작성한 컨텐츠 내의 링크 다운로드의 경우 기능 적용을 위해 <a> tag에 clsaa 속성에 link_download를 추가 해 주시면 정상 작동됩니다.
현재는 "다운로드 권한이 없습니다."로 표시 됩니다.

현재 적용된것을 기준으로 예시 입니다.
<a href="https://www.danhee.co.kr/kokoland/downloadFile.do?file_id=1274" **class="link_download"**>
    <img alt="" src="/kokoland/image/1272" style="height: 100%; width: 2000px;">
</a>
