### ISSUE TITLE
단희TV 메뉴 통합

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#147]
단희TV 메뉴를 없애 주시구요.
단희TV를 제거하고 기존 콘텐츠를 통합하려고 합니다

- 단희TV "부동산재테크정보" -> 왼쪽 콘텐츠를 부동산재테크정보 "필수기초지식" 쪽으로 옮겨주세요.
- 단희TV "재테크성공사례" -> 왼쪽 콘텐츠를 부동산재테크정보 "성공실패사례" 쪽으로 옮겨주세요.
- 단희TV "인생2막준비" -> 왼쪽 콘텐츠를 인생2막준비 "1인기업가준비" 쪽으로 옮겨주세요.

**Comment by courage-work** [comment]
메인화면, 통합검색에 노출되는 단희TV 항목도 모두 포함되는 것인가요?

**Comment by okwinus** [comment]
네 모두 포함입니다

**Comment by courage-work** [comment]
메인화면의 "매우 특별한 선물 4가지" 단희TV관련 내용이 포함되어 있습니다.
수정 문구와 이미지(모바일은 이미지임) 전달해 주시면 변경해 드리겠습니다.
