### ISSUE TITLE
모바일 부동산 재테크 강연 구성 및 디자인 변경

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#15]
부동산재테크 강연 2단 배열로 변경하고 나오는 항목 줄이기
-> 섬네일이미지(마감 7일전, 교육 제목, 교육일정, 가격 등)
(참고사이트 : http://www.i-boss.co.kr/ab-5473 모바일사이트)

**Comment by courage-work** [comment]
부동산재테크 강연 2단 배열로 변경을 좀 더 상세히 설명 부탁드립니다.
현재도 1열에 2행으로 배열되어 있습니다. 혹시 다른 의미 인가요?

**Comment by okwinus** [comment]
모바일 말씀을 드린것인데요. PC말구요.
모바일은 현재 강연 배열이 1줄에 1개 콘텐츠만 노출되고 있어요.
부동산재테크정보나 단희TV처럼
한열에 2개씩 노출되게 해달라는 말씀입니다 ^^

**Comment by okwinus** [comment]
모바일에서 "강연마감" 버튼과 섬네일 이미지가 찌그러져 나옵니다. 조치 해주시구요.
강연마감의 바탕 색상은 주황색으로 변경 해주세요.
​
그리고 강연마감 일자를 테스트 해봤는데 일자에 맞추어서 일자 변동이 안됩니다. 확인 부탁해요
