### ISSUE TITLE
프로덕션 아티클 api 연동

### ISSUE THREAD

**Issue by dg828** [courage-work/danhee#152]
![kakaotalk_20180418_101843443](https://user-images.githubusercontent.com/33975688/38909017-b32bc64e-42fd-11e8-9a0e-36e07500061a.png)

프로덕션 아티클 10개를 작성해서 검수를 받아야 하는데요.
글작성 도구에서 복사한 뒤 붙여넣기 했더니 
위 이미지처럼 나와서 아티클 정보방에 물어봤더니 api연동해서 해야한다고 하더라고요.
이 부분 부탁드리겠습니다!

**Comment by courage-work** [comment]
페이스북 인스턴트 아티클 API 연계가 현 단계에서는 진행이 불가능할 것으로 판단됩니다.
기능 구현의 가능여부에 대해 꼼꼼히 체크하지 못하고 진행된점 죄송합니다.

1. 페이스북 인스턴트 아티클의 경우 전용 MarkUp 언어가 있습니다.
 => 이는 현재 홈페이지에 있는 컨텐츠를 인스턴트 아티클로 등록할 수 없음을 의미 합니다.
 => 관련 링크 https://developers.facebook.com/docs/instant-articles/guides/importing/overview

2. 페이스북 인스턴트 아티클의 홈페이지와 연계하기 위한 방법
 => 페이스북 인스턴트 아티클 전용 게시판 제작
 => 페이스북 인스턴트 아티클 전용 게시판에 등록된 게시물은 홈페이지에 노출되지 않음
 => 아티클 전용 게시판에 등록된 정보를 페이스북과 연계

즉, 2번의 경우 페이스북에 로그인하여 인스턴트 아티클을 관리하는걸 홈페이지에서 하는거와 동일하다고 보시면 됩니다.

위의 경우를 종합해봤을때 인스턴트 아티클은 페이스북의 관리 페이지를 사용하심이 더욱 적합해 보입니다.

늦게 답변드려 죄송합니다.
