### ISSUE TITLE
소셜 로그인 수정

### ISSUE THREAD

**Issue by dg828** [courage-work/danhee#157]
안녕하세요 개발자님 
현재 홈페이지에서 SNS로 회원 가입할 때 
카톡이나 페북 또는 네이버를 클릭하면 간편회원가입할 때처럼 넘어가는데
넘어가지 말고 바로 회원가입 할 수 있게 해주세요.

다시 말씀드리면 카톡, 페북, 네이버로 회원가입 누르면 
바로 홈페이지에 로그인 되면서 홈페이지를 사용할 수 있게 해주세요.

**Comment by courage-work** [comment]
요구하신 기능은 현재의 회원가입 정책과 맞지 않는거 같습니다.
회원가입시 필수 항목으로 지정되어 있는 정보들의 수집이 불가능해 집니다.

개인정보 수집과 관계없이 메일정보, 닉네임 또는 이름만 수집한다면 처리는 가능합니다.
위 내용 고려하시어 요구사항을 다시한번 정리해주세요.

**Comment by dg828** [comment]
일단 보류하겠습니다.

**Comment by dg828** [comment]
처음에 말씀드린 것처럼 진행하겠습니다.
회원가입시 필수항목으로 설정되어 있는 것이 이메일, 전화번호, 이름 뿐인거 같아서요.
