### ISSUE TITLE
강연&상담 후기

### ISSUE THREAD

**Issue by dg828** [courage-work/danhee#159]
#154에서 수정부탁드린 내용에서 맨 아래 오른쪽으로 넘기는 표시 
">" 이거 누르면 같은 것만 계속나오네요.
이 부분은 최근 등록된 글 4개만 나오게 하지 않고 
글 하나를 클릭하면 그 글부터 다음 글 끝까지 쭉 이동할 수 있게 해주시면 좋겠습니다.

**Comment by courage-work** [comment]
글이 많아질수로 페이지 로딩에 오랜시간이 걸릴 수 있습니다.
보여지는 갯수를 무한정 늘리는 것보단 제한을 두는게 일반적입니다.
위 내용 고려하시고 의견 주시면 반영해 드리겠습니다.

**Comment by dg828** [comment]
그렇군요.
그럼 화살표 눌렀을 때 중복안되게 다음 글 6개까지만 보여지게 해주세요.
