### ISSUE TITLE
글 작성 시 이미지 크기

### ISSUE THREAD

**Issue by dg828** [courage-work/danhee#164]
https://www.danhee.co.kr/community/view.do?type=plan&category=&order=&idx=118&page=1&searchType=&keyword=

안녕하세요 개발자님~
위에 글을 예시로 말씀드리겠습니다.

관리자에서 글을 작성할 때 이미지 사이즈의 너비, 길이를 각각 100%로 수정한 뒤에 넣고 있습니다.
그런데 위 글에 보시면 인물 사진이 너무 크게 들어가 있는 걸 보실 수 있을 거에요.
이미지가 너무 커서 100%가 아닌 50%로 수정했는데 작아지지 않더라고요.
관리자에서 이미지를 줄이는 방법이 따로 있나요?

**Comment by courage-work** [comment]
예전의 요구사항에 이미지 원본 사이즈로 표시하도록 설정하는 것이 있었습니다.
즉, 글 작성시 이미지 속성에 사이즈를 지정하셔도 적용되지 않습니다.
글 작성시 사용하시는 이미지 사이즈를 줄이신 후 업로드 하시면 됩니다.

참고로 모바일에서는 단말의 최대 넓이 많큼 표시 됩니다.
