### ISSUE TITLE
컨텐츠 조회 시 팝업 창 등장 

### ISSUE THREAD

**Issue by dg828** [courage-work/danhee#167]
![20180530_111816](https://user-images.githubusercontent.com/33975688/40695233-3ccce3d8-63fb-11e8-9808-a1a422acc3c5.png)

위에는 "아이보스" 홈페이지에 나오는 팝업창입니다.
메인화면에서 카테고리를 누르고 그 안에 있는 글을 클릭한 뒤 일정시간이 지나면 저런 팝업창이 나옵니다.
저희도 저런 회원가입 유도 팝업창을 구현해보고 싶어서요.
디자인은 파워포인트로 만들어봤습니다.
![default](https://user-images.githubusercontent.com/33975688/40695775-a8306b2a-63fd-11e8-886a-b4d712cbbfd7.png)

모든 카테고리 말고 아래 이미지에서 네모 친 카테고리에만 팝업 창이 나오게 하고 싶어요.
카테고리를 클릭하고 보고싶은 글을 클릭하면 5초 뒤에 팝업 창이 나오게 해주세요.
![20180530_112851](https://user-images.githubusercontent.com/33975688/40695747-82adba88-63fd-11e8-9507-e0ef9b61c54d.png)

**Comment by courage-work** [comment]
위 요청은 디자인 건으로 제가 컨텍하는 디자이너를 통해 작업진행 하겠습니다.
비용 청구 후 작업 진행하겠습니다.

**Comment by courage-work** [comment]
모바일 화면에서의 디자인도 생각하신게 있다면 알려주세요.
없다면 위의 디자인을 축소한 형태로 작업이 진행됩니다.

**Comment by courage-work** [comment]
서비스로 진행해 드렸습니다.
