### ISSUE TITLE
상담신청 전화번호 오류

### ISSUE THREAD

**Issue by dg828** [courage-work/danhee#170]
안녕하세요 개발자님

홈페이지 통해서 상담하신 분들 전화번호가 계속 이상하게 나와서요.
전화번호 중간이랑 끝이 똑같이 나와요.
사용자 관리 들어가서 회원명 검색하면 전화번호 잘 나오는데 상담관리에서 보면 이렇게 나오더라고요.
가끔씩 회원가입 안하신분들도 계셔서 전화번호 확인이 어렵네요.

예전부터 이런 경우가 있었는데 최근에 상담자가 많아지면서 더 많이 발견됩니다.
홈페이지 오류인지 아니면 고객분들이 잘못 적은건지 모르겠어요.
확인해봐주시면 감사하겠습니다!

![20180728_121002_1](https://user-images.githubusercontent.com/33975688/43352498-721e492c-925f-11e8-952c-ad5105deb3f8.png)
![20180728_121002_2](https://user-images.githubusercontent.com/33975688/43352499-724812fc-925f-11e8-8fd9-6cc0f44b2d67.png)
![20180728_121002_3](https://user-images.githubusercontent.com/33975688/43352500-7273122c-925f-11e8-8c6a-5c0605729f94.png)
![20180728_121002_4](https://user-images.githubusercontent.com/33975688/43352501-729d9f24-925f-11e8-8f75-a5453a3fea90.png)
![20180728_121002_5](https://user-images.githubusercontent.com/33975688/43352502-72ce21ee-925f-11e8-9bea-af6ab80473c6.png)

**Comment by courage-work** [comment]
확인결과 회원가입 되신 분들의 정보를 자동입력 하는 부분에서 오류가 있었던 것으로 확인 했습니다.
모바일 홈페이지에서만 있던 문제로 확인했으며, 수정 완료하였습니다.
