### ISSUE TITLE
관리자 페이지 개발 문의

### ISSUE THREAD

**Issue by dg828** [courage-work/danhee#172]
안녕하세요 개발자님
회원들이 상담신청을 하면 관리자 페이지에서 
"신청 날짜, 이름, 전화번호, 상담유형, 상담내용"을 
전부 엑셀로 다운받아볼 수 있게 개발 부탁드리겠습니다!

그리고 현재 아래 이미지 빨간 부분 "상태"를 변경하려면
글을 클릭한 뒤에 변경이 가능한데
글을 클릭하지 않아도 상태 변경 가능하도록 개발 부탁드립니다.

![20180807_092550](https://user-images.githubusercontent.com/33975688/43747392-5aa463d6-9a24-11e8-8eb8-e0bc5fef01b8.png)

**Comment by courage-work** [comment]
기능추가 건으로 별도 견적서 보내드리며, 확정 후 진행하겠습니다.
견적서 송부는 금번 개발건이 완료된 이 후 가능할것으로 예상합니다.
우선순위 변경이 필요하면 따로 말슴하여 주시기 바랍니다.
