### ISSUE TITLE
홈페이지 수정 요청 내용

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#173]
![default](https://user-images.githubusercontent.com/33860901/46450645-54d0e700-c7cd-11e8-8ff7-95176d90a6e9.jpg)

홈페이지 최상단 로고를 위 파일로 변경 해주세요. 
현재는 단희부동산연구소 로고인데요. 캠퍼스로고로 변경 하겠습니다.

==================================================

단희부동산소개 << 메뉴를 "단희캠퍼스소개" 명칭으로 변경해주세요.
변경위치는 PC 상단메뉴바와 모바일상단메뉴 및 사이드 퀵메뉴바입니다.

==================================================

![default](https://user-images.githubusercontent.com/33860901/46450694-96fa2880-c7cd-11e8-8d09-65aa56964941.jpg)

PC하단의 "상담/컨설팅 신청하기 폼"을 이미지로 통으로 변경해서
메인에서 상담신청을 못하게 해주시구요. 이미지로 변경해서 상담신청서쪽으로 링크 걸어주세요.

그리고 PC와 모바일 하단 모두 "단희부동산연구소 이메일문의" 명칭을
"단희캠퍼스 이메일문의" 명칭으로 변경 해주세요.

==================================================

내부 업무가 많아 정신이 없다보니 개발 맡긴건도 진행을 못했는데요.
조만간 사이트 개편을 다시 해서 운영할 계획이라 정리해서 말씀 드리겠습니다.

위 업데이트 사항만 우선적으로 빠르게 변경 부탁드리겠습니다.

**Comment by courage-work** [comment]
상담/컨설팅 신청하기 폼의경우 이미지로의 대체보단 현재대로 유지하고 입력은 못하게 막고 폼 어디를 클릭하던지 상담신청서 쪽으로 이동되도록 구현하겠습니다.
원하시는 기능과는 동이하게 구성됩니다.
