### ISSUE TITLE
커뮤니티 메뉴 추가

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#19]
단희TV 메뉴 우측에 "커뮤니티" 게시판 메뉴를 추가 해주시구요.
기존 커뮤니티 게시판처럼 썸네일이 안나오는 리스트형태의 게시판을 넣어주시고
따로 커뮤니티 안에 분류를 나누지 않고 게시판 하나만 나오게 해주세요.
이 커뮤니티 게시판은 회원모두와 다같이 자유롭게 글을 작성 할 수 있는 메뉴입니다.

**Comment by okwinus** [comment]
커뮤니티 글 작성완료시 인생2막 게시판으로 이동이 되네요. 확인 부탁드려요

**Comment by courage-work** [comment]
인생2막 게시판으로 이동되는것 수정했습니다.
