### ISSUE TITLE
공유 기능중 이메일 공유 버튼 제거

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#22]
각 콘텐츠 공유시 나오는 채널중에서 "이메일" 공유 버튼을 없애주세요.
이부분도 견적 내용에 포함 해주셔도 됩니다.

**Comment by courage-work** [comment]
모바일의 경우 PC와 구성이 다르게 되어있습니다.
이메일 공유만 제거하면 될까요?

![image](https://user-images.githubusercontent.com/33827059/33019910-99252c32-ce3f-11e7-80cc-2ea6e70b2009.png)

**Comment by okwinus** [comment]
네 모바일은 카톡이 추가되어 있는것치 차이구요.
PC는 카톡 공유가 안되니까요.
PC,모바일 둘다 이메일 버튼을 없애주시면 됩니다.

그리고 가능하시면 공유버튼이 좌측 정렬되어 있어서요. 중앙정렬로 이쁘게 나오게 할 수 있으시면 부탁드려요. 당장 힘드시면 유지보수시 요청 드려도 되구요
