### ISSUE TITLE
강연등록시 일정 복수 등록 및 참여시 일정 선택

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#26]
강의 등록시 한 강의를 1달에 2~3회씩 진행 할때가 있습니다.
강연 등록시 1 강의 등록시 일정을 복수로 여러개 등록 할 수 있게 개발 해주시구요.
강의 상세페이지에서도 강의 일정을 누르면 강의 참여를 원하는 일정을 선택 할 수 있는 폼이 추가되었으면 합니다.
우측 상단 강의 일정 안내 부분을 수정 하면 될것 같습니다.
(모바일 동일)

**Comment by courage-work** [comment]
강연일정을 복수개로 등록하는 것은 회차를 구분하는 것이 맞나요?
회차로 구분을 한다면 회차별 관리해야 하는 정보는 무엇이 있을까요?
강연일정외에 회차별 모집인원, 신청인원도 회차와 함께 구분이 필요할거 같아 문의 드립니다.
위 정보 외에 회차별 정보로 구분해야 하는 정보가 있다면 알려주세요.

회차정보가 추가될 경우 목록에 표시될 방법에 대해서도 확정 부탁드립니다.
예를 들어 2회차 정보로 등록할경우 목록에 표시되는 일정의 표시방법 등에 대한 확정이 필요합니다.

**Comment by okwinus** [comment]
회차로 구분 하는것은 아니구요. 똑같은 강읭를 월 몇회 진행 하는것입니다.
