### ISSUE TITLE
단희TV 게시판 확장

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#3]
단희TV 메뉴를 직장인커뮤니티 게시판처럼 4개 게시판으로 확장

**Comment by okwinus** [comment]
단희TV type2 ~ type4 각각의 메뉴버튼을 누를시 버튼 색상이 안변합니다. 
인생2막준비 메뉴랑 비교 해서 검토 해보시면 될 것 같아요. 확인 부탁합니다.

**Comment by courage-work** [comment]
버튼 누름이 표시되도록 수정했습니다.
