### ISSUE TITLE
회원 프로필 이미지 등급별 분리

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#30]
프로필 회원 사진에 본인의 FAMILY, YEAR, VIP 회원등급이 표시되게 해주세요.(아래 디자인 참고)
(프로필 사진이 표기되는 모든 부분에 아래 등급도 같이 표시되게 동기화 해주세요. ex: 본인 작성글, 댓글 등)

![image](https://user-images.githubusercontent.com/33827059/33020901-46d88c7c-ce43-11e7-854b-b4f36d3d76f0.png)
![image](https://user-images.githubusercontent.com/33827059/33020905-4879dec8-ce43-11e7-8e08-2fd14a24bfb7.png)
![image](https://user-images.githubusercontent.com/33827059/33020908-49dc4c9c-ce43-11e7-8866-dcd90258fe65.png)

**Comment by courage-work** [comment]
비회원의 경우 어떻게 표기를 해야할까요?

**Comment by okwinus** [comment]
비회원은 로그인 조차 안되어 있는 사람이라 마이페이지를 확인 할수 없기 때문에 표기할 부분이 없습니다.

**Comment by courage-work** [comment]
요구사항이 마이페이지 외 프로필 사진이 표기되는 모든 페이지를 변경하는 것으로 말씀해 주셨습니다.
강연&상담 후기의 경우 비회원도 작성이 가능합니다.

**Comment by okwinus** [comment]
아~ 넵 
댓글이나 글에서는 아무런 등급 표시가 없습니다.
