### ISSUE TITLE
카카오 알림톡

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#33]
알림톡 개발은 별도 발송 서버를 구축 해야 하는걸로 알고 있는데요.
현재 관리자에 기능을 넣어주시거나 별도 발송 페이지를 개발 해주셔도 됩니다.
서버 임대나 발송 시스템은 어떻게 구축되는건지 궁금합니다.

그리고 알림톡 발송 메세지는 사전에 카카오톡 본사에 검수를 받아야 하는걸로 알고 있어서요.

개발하려는 시스템은 수동 발송이 아닌 자동화 발송 시스템입니다.
아래 시점에 자동으로 발송되게 원하구요.
알림톡 메세지 내용은 추후 관리자에서 수정 하여 재검토 가능한지도 궁금합니다.
현재 이용하고 있는 "포스트맨"이라는 알림톡 발송 시스템은
기존에 검수허락이 받아져 있는 메세지를 자동으로 발송 가능하고
추가 내용이 필요할경우 포스트맨에서 알림톡 메세지 작성 후 검토 과정을 3~4일 거칩니다.
시스템이 어떻게 되는지 알고 게시면 답 부탁드리구요.
아래 내용에 자동화 발송되길 원합니다.

※ 그리고 등록된 고객 개인정보에 맞추어서 자동변환 되어 나가는 알림톡도 원합니다.
예를들어 고객이름이 자동 변환되어 발송 되는 그런 시스템입니다. 고객이름뿐 아니라 강의정보 등 여러정보가 있습니다.

= 자동화 알림톡 메세지(상세 내용까지 바로 필요한지도 얘기 해주세요. 추후 등록/수정 가능하다면 나중에 등록 하겠습니다.)
- 회원가입시
- 로그인시
- 등업시(FAMILY->MEMBER->VIP)
- 부동산재테크 강연 -> 교육신청 폼 작성 완료시
- 부동산재테크 강연 -> 관리자 승인처리 시 "교육 최종 접수 완료"
- 부동산재테크 상담 접수중
- 부동산재테크 상담 접수완료
- VIP재테크정보 상담 접수중
- VIP재테크정보 상담 접수완료
- 포인트 소진시(콘텐츠 열람시 포인트 소진)
- 포인트 획득시
등

이외에도 필요시 추후 수정/등록을 가능 했으면 합니다.

**Comment by courage-work** [comment]
알림톡 발송을 위해선 중계사의 서비스를 이용해야 합니다.
어느 중계사의 서비스를 이용하실 예정인가요?

**Comment by okwinus** [comment]
알림톡 중계사라는게 대행업체 얘기하시는거죠?
어디다 해야 될지 잘 모르겠어서요. 알림톡 개발시스템이 어떻게 되는건지 잘 모르겠네요.
추천해줄만한 업체라던가 아는곳 있으시면 그대로 진행 하고 싶습니다.

**Comment by courage-work** [comment]
카카오 알림톡은 딜러사(중계사)를 통해 서비스 이용이 가능합니다.
아래 링크에서 딜러사 확인하시고 견적 받아보고시 결정되면 알려주세요.
참고로 딜러사별 서비스 이용비용이 다를 수 있습니다.

요구하시는 기능 구현을 위해선 반드시 API 또는 Agent 방식의 발송 기능이 있어야 합니다.
대부분 딜러사가 제공하고 있으니 결정하실때 확인 부탁드립니다.
https://bizmessage.kakao.com/#none

**Comment by okwinus** [comment]
https://www.bizmsg.kr/main/
ID : kokoland 
PS : Danhee2018

들어가셔서 로그인 하시면
왼쪽 하단에 개발지원 API가이드 파일이 있어요. 확인 하셔서 개발 진행 해주시면 될 것 같구요.
결제 필요하거나 제가 해야될 부분 있으면 얘기해주세요 ^^

**Comment by courage-work** [comment]
1. 현재 API 연계는 완료되었으나, 가이드 대로 준수하여 발송하였는데 카카오 템플릿과의 불일치로 오류가 발생되고 있습니다.
위 문제는 bizmsg에 Q&A에 등록해둔 상태 입니다. 답변 확인되는 대로 조치하겠습니다. (API 연계의 문제는 아닙니다.)

2. 위에 언급해주신 알림톡 발송을 위해선 템플릿이 등록 되어야 진행 가능합니다. 템플릿 등록을 완료하신 후 알려주시면 추가 진행하겠습니다.

**Comment by okwinus** [comment]
알림톡 발송에 관하여 아직 내용이 확정이 안되서요.
현재 등록되어 있는 승인 템플릿 2개로 테스트 할 수 있을까요?
중간 중간 알림톡 발송 내용이 확정되면 부분적으로 유지보수로 안내 드리려고 합니다.
