### ISSUE TITLE
부동산재테크정보, 노하우정보집, 단희TV 컨텐츠 열람권한 지정

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#36]
특정 등급 회원만 볼 수 있는 권한을 각 콘텐츠별로 FAMILY(일반회원) / MEMBER(연간유료회원) / VIP(유료회원) 
콘텐츠를 등록시 콘텐츠별로 권한 등록을 할 수 있게 개발 부탁합니다.

3개 게시판만 해당됩니다.

**Comment by courage-work** [comment]
컨텐츠 별로 권한을 지정할 경우 권한이 없는 사용자들(비로그인사용자 제외)은 포인트 결제 후 열람이 가능한가요?
#35 요구사항과 비슷한듯 합니다.
확인 부탁드립니다.

**Comment by okwinus** [comment]
연간유료회원과 VIP유료회원은 모든 유무료 콘텐츠를 열람 가능한 정액방식의 회원이구요.
등급 권한 자체를 주는 것이구요.

일반회원 같은 경우 포인트로 열람이 가능합니다.

콘텐츠별로 권한을 등록 하게 해준다는것은 특정 콘텐츠가
어떤 회원등급부터 볼 수 있는지 권한을 부여 해주는것이구요.
