### ISSUE TITLE
강연 배너등록 기능 추가

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#38]
- [x] 상단에는 별도로 배너를 따로 등록 할 수 있게 해주세요. 현재는 내용을 바로 등록 하게 되어 있는데요.

- [x] PC 최상단에 강의소개 배너 등록 , 그다음 버튼, 그다음 강의 상세내용 등 이렇게 나왔으면 합니다.
모바일 최상단에 강의소개 배너 등록, 그다음 강의 일정, 시간 등 강의소개 내용, 그다음 버튼, 그다음 강의 상세내용

**Comment by courage-work** [comment]
등록한 배너는 어떤형식으로 표시하면 될까요?
참고할만한 사이트나 이미지가 있다면 알려주세요.

**Comment by okwinus** [comment]
문의내용 전에 답변 드린 내용 같아서요. 다시 답  안드려도 되죠?

**Comment by okwinus** [comment]
강연 상세내용 최상단에 배너등록을 따로 하기로 했는데 관리자에 썸네일외에
강연 상단 배너 등록 기능이 없네요.
