### ISSUE TITLE
(유지보수,모바일) 좋아요, 댓글, 공유 기기 해상도별로 숫자 겹치는것

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#41]
아이폰4, LG G4 등 해상도가 낮은 구형기기에서 확인시 조회수,댓글,공유수 3자리 이상 넘어가면 계속 겹처서 나옵니다. 
이미지값에 % 값을 주어서 기기마다 자동 리사이징 되게 하는것처럼 조회수,댓글,공유수도 퍼센트 값을 넣을수 있다면 기기마다 자동으로 크기가 조정되도록 해주세요. 3자리 4자리 넘어가면 아예 보이지 않습니다.
(전화로 안내드렸던 내용이에요.)

유지보수가 아닌 개발이라면 따로 안내 해주세요 ^^

**Comment by courage-work** [comment]
해상도에 따라 변동되도록 수정했습니다.

**Comment by okwinus** [comment]
조회수, 좋아요만 남고 댓글, 공유가 빠짐으로 인해서
해상도 설정이 바뀌는건 아닌지 해서요.
​
그리고 4자리 숫자까지만 모두 나오고 만단위부터는 2만, 2.1만 이렇게 변경 해달라고 부탁드렸기  때문에
변경 되는부분에 추가 개발이 들어가면 별도로 말씀 해주세요.
