### ISSUE TITLE
(유지보수, PC&모바일)(부동산재테크정보) 리스트 화면에서 댓글 카운팅이 안됩니다.

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#42]
리스트 화면에서 댓글 카운팅이 안됩니다.

**Comment by courage-work** [comment]
제가 확인한 PC와 모바일에서의 목록은 댓글 카운트가 정상적으로 표시됩니다.
어느 메뉴의 목록에서 안되는 것인지 확인 부탁드립니다.

**Comment by okwinus** [comment]
부동산재테크정보 메뉴 목록에서 댓글 카운팅이 안올라갑니다

**Comment by courage-work** [comment]
앗.. 제목에 메뉴명을 기재해 주셨는데.. 제가 꼼꼼히 보지 못했네요. ^^;
댓글 카운트와 더블어 좋아요 카운트도 함께 수정했습니다.
