### ISSUE TITLE
(유지보수, 모바일)(페이스북공유) 페이스북 공유가 안됩니다. 에러 메세지가 자꾸 뜨네요.

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#45]
페이스북 공유가 안됩니다. 에러 메세지가 자꾸 뜨네요.
전에 원개발자분이 페이스북 개발자 관리자에서 뭘 안했다고 한것 같은데
확인좀 부탁드려요. 필요시 아이디, 비번도 공유 드리겠습니다.

**Comment by courage-work** [comment]
공유 기능은 지정된 Domain만 가능하기 때문에 테스트를 제 개발서버인 danhee.courage.pe.kr에서 하신것이면 오류나는게 맞습니다.
danhee.co.kr 에서도 오류가 발생된다면 다시 알려주시기 바랍니다.
제가 확인해보니 danhee.co.kr에서는 작동하는 것으로 확인했습니다.

**Comment by okwinus** [comment]
크롬브라우저에서 되는건 확인 했는데
네이버웨일에서는 안되네요. 원래 이런건가요??;;

그리고 페이스북게시 버튼을 눌렀을때 창이 닫히지 않고 계속 머무르네요.
다른 사이트 페이스북 공유도 글작성 완료시 창이 닫히더라구요.
테스트는  danhewe.co.kr 에서 했습니다.
