### ISSUE TITLE
(유지보수, PC&모바일)(페이스북공유) 공유시 콘텐츠가 안나옵니다

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#46]
제목,내용,이미지 모두 공유 안되구요, 어떤 콘텐츠를 공유하든 똑같은 메세지만 공유 됩니다.
(페이스북 게시 버튼을 눌러도 게시 활성화가 되면서 사라지지 않구요.)

**Comment by courage-work** [comment]
페이스북 개발자 ID/PW를 카톡으로 보내주세요.
몇가지 확인 후 기능을 수정해야 합니다.
여기에 ID/PW를 기재하시면 안됩니다. 이 페이지는 공개된 페이지 입니다.
