### ISSUE TITLE
(유지보수, PC)(노하우정보집) 리스트 화면 점검

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#53]
노하우정보집 리스트 정렬 화면에서 보면
왼쪽 줄이 안나오네요. 왼쪽줄이 같이 노출될 수 있게 수정 해주세요.

**Comment by courage-work** [comment]
왼쪽줄이 나오지 않는게 어떤건지 이미지 첨부 가능하다면 부탁드립니다.
확인하신 브라우져 정보도 같이 부탁드려요.

**Comment by okwinus** [comment]
카카오톡으로 메세지 드렸습니다.
