### ISSUE TITLE
<더보기> 수정

### ISSUE THREAD

**Issue by dg828** [courage-work/danhee#56]
(모든 메뉴 동일) 
아래에 있는 컨텐츠를 보기 위해서는 <더보기>를 누르고 봐야합니다.
<더보기>를 누르고 보고 싶은 컨텐츠를 클릭하면 컨텐츠 상세페이지로 넘어가게 되죠.
컨텐츠를 다 보고 다른 컨텐츠를 보기 위해서 뒤로가기를 누릅니다.

여기에서 문제가 생깁니다.
뒤로가기를 누르면 또 다시 <더보기>를 눌러서 아래 컨텐츠를 확인해야하는 번거로움이 있습니다.
뒤로가기를 누르면 전에 <더보기>를 눌렀던 위치로 넘어갈 수 있도록 수정해주시면 감사하겠습니다.

**Comment by courage-work** [comment]
신규로 기능수정 요청하신 내용(#61)과 위 수정요청 하신 내용을 종합해서 문의 드립니다.
현재 썸네일 페이지의 로딩방식은 페이징 처리가 아닌 더보기 클릭시 새로고침 없이 컨텐츠가 존재하는 만큼 표시하도록 되어 있습니다.
즉, 페이스북과 트위터 (자동으로 로딩되긴 합니다) 와 같은 기능이라고 보시면 됩니다.

현재 처럼 더보기를 눌러 표시하는 방식은 뒤로가기를 했을때 이전 페이지를 그대로 유지할 수 없습니다. 이는 페이스북과 트위터도 마찬가지 입니다.

현재의 더보기 기능과 무한스크롤의 기능은 정보의 성격에 따라 적용해야 하는 기능 입니다.
실시간으로 정보가 생성되고 그 양이 셀수없이 많은 경우 페이지가 무의미 하기 때문에 목록에 접근했을때 최신의 정보를 보여주도록 되어 있습니다.
즉, 트위터나 페이스북의 경우 "지금 목록에 3페이지 들어가서 3번째 글 봐바~" 이런 접근을 하지 않게되죠.. 그래서 목록의 유지가 필요가 없는 성격입니다.

하지만, danhee 부동산의 경우 경우에 따라서는 사용자들이 목록의 URL을 공유하게 될 수 있습니다. 이럴 경우 페이징 정보가 함께 포함되어 공유하고자 하는 페이지가 떠야 하겠죠.
또한, 정보의 제공이 실시간 대량이 아니기 때문에 "홈페이지 단희TV 3번째 페이지 보세요" 이런 식의 접근또한 근 시일이내에는 가능하게 됩니다.

결론적으로 말씀드리면, 현재 상태에서 뒤로가기 시 목록 유지가 불가 합니다.
위 사항 고려하시어 의견 부탁드립니다.
