### ISSUE TITLE
(유지보수)(PC,모바일) 메인 메뉴 정렬 수정 요청

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#57]
PC, 모바일 메인 화면에서

- 단희쌤의 인생스토리
- 경력 이력 나와있는 숫자 6개 메뉴
- 교육 후기
- 재테크 성공사례
- 부동산재테크 상담 신청하기

위 5개 메뉴를 PC, 모바일 메인에서 없애주세요.
소스 자체를 삭제 하지는 말아주시구요.

오픈 초기에는 콘텐츠 위주로 정렬을 할거라
서비스 관련 메뉴는 메인에서 없애려고 합니다.

**Comment by courage-work** [comment]
요청에 의해 취소합니다.
