### ISSUE TITLE
★ 각 콘텐츠 하단에 더보기 버튼 수정 요청

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#61]
더보기 버튼을 눌러야 다음 콘텐츠가 나와서 번거로운것 같아서요.
더보기 버튼을 없애고 PC에서는 마우스 스크롤을 내리면 자동으로 콘텐츠가 나오게 하고
모바일에서는 손가락 드래그를 하면 자동으로 나오게

페이스북 피드 콘텐츠처럼 자동으로 나오게 가능할까요?
유지보수안에서 가능한지 아니면 따로 개발해야 하는지 말씀 해주시구요.
개발해야 하면 견적좀 말씀 해주세요~

**Comment by courage-work** [comment]
해당건은 기능 추가건으로 보안관련해서 추가견적 드릴때 포함하여 드리겠습니다.

**Comment by okwinus** [comment]
알겠습니다 ^^
