### ISSUE TITLE
(유지보수) 에러 수정 요청

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#63]
모바일과 PC에서 회원가입시

소셜로그인 버튼이 됬었는데 작동이 아예 안되네요. 

카카오톡, 네이버, 페이스북 모두 안됩니다.

그리고 모바일에서는 네이버 아이콘이 깨저서 나오네요. 확인 부탁드려요~

그리고 단희쌤 언론보도&수상 썸네일 정렬이  PC 하고 모바일에서 깨저서 나오네요...;;

**Comment by courage-work** [comment]
http 설정에서 https으로 변경하면서 URL이 변경되어 발생되었던 문제로 조치 했습니다.
