### ISSUE TITLE
(유지보수) 인생2막준비 관리자페이지

### ISSUE THREAD

**Issue by dg828** [courage-work/danhee#64]
관리자 페이지에서 인생2막준비들어간 후에 어떤 카테고리든 
네이버 블로그에서 글을 복사 붙이기 하면 
글씨가 너무 조그맣게 나옵니다. 
복사 붙이기 하면 블로그 글에 있는 글씨 크기처럼 나오게 수정 부탁드려요.

그리고 관리자페이지 인생2막준비에서
글에 수정버튼이 없어요. 추가부탁드립니다~

**Comment by courage-work** [comment]
복사&붙여넣기시 글씨의 사이즈 및 스타일은 에디터에서 수정하셔야 합니다.
기능적으로 수정할 수 없는 사항 입니다.

수정기능은 기존에 없던 기능으로 "기능수정"건으로 분류하여 진행하겠습니다.
