### ISSUE TITLE
[유지보수] 노하우 정보집 컨텐츠 이미지 사이즈 

### ISSUE THREAD

**Issue by dg828** [courage-work/danhee#67]
노하우 정보집에 컨텐츠를 올리려고 관리자에 들어가서 이미지를 업로드하다가 오류를 발견했습니다.
이미지를 업로드 하고 완료를 누르면 이미지가 화면을 초과해서 짤려서 보입니다.
비율을 유지한채 사이즈를 조정해도 계속 똑같이 나오네요.
네이버 블로그에 올린 후에 복사 붙여넣기 하면 잘 나옵니다.

**Comment by courage-work** [comment]
해당 오류를 제가 재현해 볼 수 있도록 테스트 하셨던 이미지를 schkkh@naver.com 으로 전달 부탁드립니다.
