### ISSUE TITLE
전체메뉴 동기화

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#68]
현재 적용된 전체메뉴 보시면 메뉴명이 일부 변경 되었습니다.
나머지 하위메뉴들의 메뉴도 전체메뉴를 기준으로 모두 통일하게 적용 해주세요.

**Comment by courage-work** [comment]
모바일과 PC 모두 해당되는 사항일까요?
변경 기준을 어느 메뉴로 하면될지 안내 부탁드립니다.
