### ISSUE TITLE
PC 상담 통합검색 메뉴 

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#76]
![screenshot 2018-01-26 at 14 11 30](https://user-images.githubusercontent.com/33860901/35426003-21c1655a-02a3-11e8-941e-6e101d9a68a8.png)

위 형태로 변경 부탁드려요. 개발 내용이니 추가 견적 필요하면 말씀 해주시구요

**Comment by courage-work** [comment]
2차 기능개선때 포함되었던 내용으로 확인이 됩니다.
지금은 홈페이지에 반영되어 있는데 추가 수정이 필요한 부분이 있다면 안내 부탁드립니다.
