### ISSUE TITLE
기타&제휴문의 게시판 타입 변경

### ISSUE THREAD

**Issue by courage-work** [courage-work/danhee#8]
리스트 게시판 형태가 아닌 폼 작성으로 변경 해주세요. 
작성 항목은 "이름, 연락처, 이메일주소, 제목, 내용" 
기타&제휴문의 들어가면 위 항목을 바로 작성 해서 
관리자 메일로 발송 될 수 있도록 해주세요.
(기존 공개&비공개는 개발 할 필요가 없습니다.)

**Comment by okwinus** [comment]
로그인 상태에서 제휴문의 들어갈시 성함하고 메일주소는 자동 기입되는데
연락처는 자동기입이 안되서요. 연락처도 자동기입되기 부탁드려요~

**Comment by courage-work** [comment]
연락처도 자동 기입되도록 변경했습니다.

**Comment by okwinus** [comment]
관리자 어떤 메일로 가는거죠? 설정하는곳이 없어 보여서요.
