### ISSUE TITLE
PC 메인 단희TV 표시방법 변경

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#80]
![screenshot 2018-02-06 at 15 45 39](https://user-images.githubusercontent.com/33860901/35845248-ebabf2fe-0b54-11e8-843e-c64eb511a899.png)

현재 썸네일 이미지에 파란색 이미지가 덧 씌워저 있는데요.
덧 씌워진 이미지를 없애주세요.
그리고 현재 단희TV 썸네일 이미지는 중앙에 재생 표시가 나와있는데
메인에서는 그 이미지가 안나오네요. 수정된 이미지가 안나오는 부분 체크 해주세요.

그리고 PC 메인 단희TV에도 각 콘텐츠 하단에 조회수, 좋아요 표시가 나오게 해주세요.

**Comment by courage-work** [comment]
덧씌워진 이미지는 썸네일 이미지의 색상에 상관없이 제목과 플레이 아이콘이 잘 보이도록 하는 역할을 하고 있습니다.
덧씌워진 이미지를 제거할 경우 썸네일 이미지의 색상에 따라 제목과 플레이 아이콘의 잘 보여지지 않을 수 있습니다.
위 사항 고려하시어 요청사항 확인 부탁드립니다.
