### ISSUE TITLE
PC+모바일 콘텐츠 정렬 변경

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#83]
![pc](https://user-images.githubusercontent.com/33860901/36013030-3d98214e-0da5-11e8-992f-5d628ffe546f.png)

메인에서 부동산재테크 정보 부분을
위 이미지처럼 부동산재테크 정보 1줄
인생2막준비 정보 1줄
이런 형태로 변경 ㅎ ㅐ주시구요.

모바일 메인도 부동산재테크 정보 하단에 인생2막 준비 콘텐츠가 나오게 추가 해주세요.
노출형태는 부동산재테크정보랑 동일 하면 됩니다.

**Comment by courage-work** [comment]
PC수정은 유지보수 범위이고 모바일은 기능수정 범위라 기능수정으로 분류했습니다.
고려해서 견적은 낮게 측정 하겠습니다.
