### ISSUE TITLE
PC교육 페이지 에러 수정

### ISSUE THREAD

**Issue by okwinus** [courage-work/danhee#99]
![screenshot 2018-02-19 at 13 40 42](https://user-images.githubusercontent.com/33860901/36362713-80ecbaa4-157a-11e8-97d8-554ae21cc765.png)

강의내용 강사소개 탭은 눌르면 제대로 되는데
강연장소, 관련강의, 교육후기는 눌러도 해당 탭의 색상이 파란색으로 안나오네요.
체크 부탁드리구요.

전체적으로 탭 버튼을 누르면 탭 내용의 상단 부분이 잘려서 노출될때가 있네요.
간격이 잘 맞을수 있도록 수정 부탁드리구요.

강의 신청 완료시 "완료팝업"만 뜨는것이 아니라 강의 신청 완료 페이지까지 만들려고 하는데요.
이 부분도 개발 요청 드리구요. 추가 비용이 있다면 말씀 해주세요.

**Comment by courage-work** [comment]
완료 페이지 구성과 표시할 내용 안내 바랍니다.
